class_name Javelot
extends Node2D
## Laser triangulaire qui détruit les briques sur son passage


const vitesse_ascendante: float = 1000.0 # px/sec
const degats: int = 2


func _physics_process(delta: float) -> void:
	position.y -= delta * vitesse_ascendante


func _auto_detruire() -> void:
	queue_free()


func _quand_corps_entre_dans_zone_destructive(corps: Node2D) -> void:
	if corps is Brique: # toujours vrai si calque collision actif
		var brique: Brique = corps as Brique
		brique.frapper(degats)


func _quand_verificateur_visibilite_detecte_sortie_ecran() -> void:
	_auto_detruire()
